// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Auth: typeof import('./components/Auth/index.vue')['default']
    AuthAll: typeof import('./components/AuthAll/index.vue')['default']
    BatchActionBar: typeof import('./components/BatchActionBar/index.vue')['default']
    CommonSelect: typeof import('./components/CommonSelect/index.vue')['default']
    ConmonTable: typeof import('./components/ConmonTable/index.vue')['default']
    Copyright: typeof import('./components/Copyright/index.vue')['default']
    FixedActionBar: typeof import('./components/FixedActionBar/index.vue')['default']
    ImagePreview: typeof import('./components/ImagePreview/index.vue')['default']
    ImagesUpload: typeof import('./components/ImagesUpload/index.vue')['default']
    ImportExcel: typeof import('./components/ImportExcel/index.vue')['default']
    PageHeader: typeof import('./components/PageHeader/index.vue')['default']
    PageMain: typeof import('./components/PageMain/index.vue')['default']
    PcasCascader: typeof import('./components/PcasCascader/index.vue')['default']
    Quarter: typeof import('./components/Quarter/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar/index.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    SystemInfo: typeof import('./components/SystemInfo/index.vue')['default']
    Trend: typeof import('./components/Trend/index.vue')['default']
    UploadFile: typeof import('./components/uploadFile/index.vue')['default']
    UploadImg: typeof import('./components/uploadImg/index.vue')['default']
  }
}
